from setuptools import setup

APP = ['appsweeper.py']
DATA_FILES = []

OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'assets/icon.icns',          # generated by make_icon.sh
    'packages': [],
    'includes': ['tkinter', 'tkinter.ttk', 'tkinter.messagebox'],
    'excludes': ['matplotlib', 'numpy', 'scipy', 'PIL', 'pytest'],
    'plist': {
        'CFBundleName':             'AppSweeper',
        'CFBundleDisplayName':      'AppSweeper',
        'CFBundleGetInfoString':    'Smart App Closer for macOS',
        'CFBundleIdentifier':       'com.github.appsweeper',
        'CFBundleVersion':          '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSAppleEventsUsageDescription': (
            'AppSweeper needs permission to send quit commands to other applications.'
        ),
        'NSHumanReadableCopyright': '© 2026 AppSweeper — MIT License',
        'NSHighResolutionCapable':  True,
        'LSMinimumSystemVersion':   '12.0',
    }
}

setup(
    name='AppSweeper',
    version='1.0.0',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
